name: CI
on:
  push:
    branches: [ main ]

jobs:
        - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Cache Buildozer global directory
        uses: actions/cache@v3  # Updated to v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v3  # Updated to v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.DATE }}-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer directory
      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.DATE }}-${{ hashFiles('buildozer.spec') }}

      # Build using Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      # Upload build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
